# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gH1y9RSAgVPQWeS0X87RIazKWbsgGl4A
"""

!pip install ncon

import numpy as np
from ncon import ncon
import time

A = np.random.rand(2, 2, 2)
B = np.random.rand(2, 2, 2, 2)
C = np.random.rand(2, 2, 2, 2)
E = np.random.rand(2, 2, 2)
D = np.random.rand(2, 2, 2)

#Способ 1
start = time.time()
result_for = np.zeros((2, 2, 2))
for i in range(2):
  for j in range(2):
    for k in range(2):
      for m in range(2):
        for l in range(2):
          for n in range(2):
            for f in range(2):
              for g in range(2):
                for q in range(2):
                  for s in range(2):
                    result_for[i, j, k] += A[m, l, i] * B[m, n, f, j] * C[l, n, g, q] * E[f, g ,s] * D[s, q, k]
time_for = time.time() - start 
print("Валентность(правильный ответ - 3): ", len(result_for.shape))
print("Результирующий тензор:\n", result_for)

#Способ 2
start = time.time()
result_ncon = ncon((A, B, C, D, E), [[1, 2, -1], [1, 3, 4, -2], [2, 3, 5, 7], [6, 7, -3], [4, 5, 6]])

time_ncon = time.time()-start
print("Валентность(правильный ответ - 3): ", len(result_ncon.shape))
print("Результирующий тензор:\n", result_ncon)

#Способ 3
start = time.time()
A1 = A.reshape(2, 4).T
B1 = B.reshape(2, 8)
AB = A1 @ B1

AB1 = AB.reshape(4, 8).T
C1 = C.reshape(4, 4)
ABC = AB1 @ C1

ABC1 = ABC.reshape(4, 8).T
E1 = E.reshape(4, 2)
ABCE = ABC1 @ E1

ABCE1 = ABCE.reshape(4, 4)
D1 = D.reshape(4, 2)
ABCED = (ABCE1 @ D1).reshape(2, 2, 2)

time_reshape = time.time() - start 
ABCED

#Сравнение способов
print("Время выполнения работы с for = ", time_for)
print("Время выполнения работы с reshape = ", time_reshape)
print("Время выполнения работы с ncon = ", time_ncon)

